variable "region" {}
variable "location" {}
variable "environment" {}
variable "az1" {}
variable "az2" {}
variable "project" {}
variable "cidr-prefix" {}
variable "bucket" {}
variable "bucket-path" {}
